"""Criar tabelas

Revision ID: 5ee7981425a2
Revises: 7902cbbd3383
Create Date: 2025-05-06 22:18:50.695027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee7981425a2'
down_revision: Union[str, None] = '7902cbbd3383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('last_transaction_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_id'), 'transport', ['id'], unique=False)
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'rg', ['rg_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'cpf', ['cpf_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'vaccination_card', ['vaccination_card_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'cnh', ['cnh_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_transport_id'), table_name='transport')
    op.drop_table('transport')
    # ### end Alembic commands ###
