"""Criar tabelas

Revision ID: 7902cbbd3383
Revises: a864d5f80f9c
Create Date: 2025-05-06 21:08:54.647808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7902cbbd3383'
down_revision: Union[str, None] = 'a864d5f80f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'vaccination_card', ['vaccination_card_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'rg', ['rg_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'cpf', ['cpf_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'cnh', ['cnh_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    # ### end Alembic commands ###
