"""Criar tabelas

Revision ID: b90444402ade
Revises: b8552cac3158
Create Date: 2025-05-06 19:38:59.390895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90444402ade'
down_revision: Union[str, None] = 'b8552cac3158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=11), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('issued_by', sa.String(length=50), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cnh_id'), 'cnh', ['id'], unique=False)
    op.create_index(op.f('ix_cnh_number'), 'cnh', ['number'], unique=True)
    op.create_table('cpf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=11), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('issued_by', sa.String(length=50), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpf_id'), 'cpf', ['id'], unique=False)
    op.create_index(op.f('ix_cpf_number'), 'cpf', ['number'], unique=True)
    op.create_table('rg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('issued_by', sa.String(length=50), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rg_id'), 'rg', ['id'], unique=False)
    op.create_index(op.f('ix_rg_number'), 'rg', ['number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vaccination_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=11), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccination_card_id'), 'vaccination_card', ['id'], unique=False)
    op.create_index(op.f('ix_vaccination_card_number'), 'vaccination_card', ['number'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cpf_id', sa.Integer(), nullable=True),
    sa.Column('rg_id', sa.Integer(), nullable=True),
    sa.Column('cnh_id', sa.Integer(), nullable=True),
    sa.Column('vaccination_card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cnh_id'], ['cnh.id'], ),
    sa.ForeignKeyConstraint(['cpf_id'], ['cpf.id'], ),
    sa.ForeignKeyConstraint(['rg_id'], ['rg.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vaccination_card_id'], ['vaccination_card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_vaccination_card_number'), table_name='vaccination_card')
    op.drop_index(op.f('ix_vaccination_card_id'), table_name='vaccination_card')
    op.drop_table('vaccination_card')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rg_number'), table_name='rg')
    op.drop_index(op.f('ix_rg_id'), table_name='rg')
    op.drop_table('rg')
    op.drop_index(op.f('ix_cpf_number'), table_name='cpf')
    op.drop_index(op.f('ix_cpf_id'), table_name='cpf')
    op.drop_table('cpf')
    op.drop_index(op.f('ix_cnh_number'), table_name='cnh')
    op.drop_index(op.f('ix_cnh_id'), table_name='cnh')
    op.drop_table('cnh')
    # ### end Alembic commands ###
