name: CI - Run Tests

on:
  push:
    branches:
      - feat-teste-gabriel-herdeiro
  pull_request:
    branches:
      - feat-teste-gabriel-herdeiro

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testeSenhaInfinita
          MYSQL_DATABASE: carteira_digital
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..10}; do
          if mysqladmin ping -h 127.0.0.1 --silent; then
            echo "MySQL is ready!";
            break;
          fi;
          echo "Waiting for MySQL...";
          sleep 5;
        done

    - name: Run migrations
      run: |
        alembic upgrade head

    - name: Run tests
      run: |
        pytest