name: CI - Run Tests

on:
  push:
    branches:
      - feat-teste-gabriel-herdeiro
  pull_request:
    branches:
      - feat-teste-gabriel-herdeiro

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testeSenhaInfinita
          MYSQL_DATABASE: carteira_digital
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3  --init-file /docker-entrypoint-initdb.d/init.sql
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Dockerize
      run: |
        wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
        tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
        rm dockerize-linux-amd64-v0.6.1.tar.gz

    - name: Wait for MySQL to be ready
      run: |
        dockerize -wait tcp://db:3306 -timeout 120s

    - name: Run migrations
      env:
        DATABASE_URL: mysql+pymysql://root:testeSenhaInfinita@127.0.0.1:3306/carteira_digital
      run: |
        alembic upgrade head

    - name: Run tests
      env:
        DATABASE_URL: mysql+pymysql://root:testeSenhaInfinita@127.0.0.1:3306/carteira_digital
      run: |
        pytest